language: python
python:
    - 2.6
    - 2.7
    - 3.3
env:
    - DJANGO=1.4
    - DJANGO=1.5

install:
    - pip install -q -r "test_requirements/django-$DJANGO.txt" --use-mirrors

script:
    python runtests.py

after_success:
  - coveralls