# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
    - 2.7
    - 3.3
    - 3.4

env:
  matrix:
    - DJANGO=1.7 DJANGOCMS=3
    - DJANGO=1.8 DJANGOCMS=3



install:
  - pip install -q -r "test_requirements/django-$DJANGO.txt"


script:
  - coverage run ./runtests.py
  - ./lint.sh
  - coverage report

after_success:
  - coveralls