language: python
python:
    - 2.6
    - 2.7

env:
    - DJANGO=1.4 DJANGOCMS=3
    - DJANGO=1.5 DJANGOCMS=3
    - DJANGO=1.6 DJANGOCMS=3

install:
    - pip install -q -r "test_requirements/django-$DJANGO.txt"

script:
    - coverage run ./runtests.py
    - coverage report

branches:
  only:
    - master

after_success:
    - coveralls