# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
    - 2.7
    - 3.3
    - 3.4

env:
  matrix:
    - DJANGO=1.4 DJANGOCMS=3
    - DJANGO=1.6 DJANGOCMS=3
    - DJANGO=1.7 DJANGOCMS=3

# https://docs.djangoproject.com/en/1.7/faq/install/
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4 DJANGOCMS=3
    - python: 3.4
      env: DJANGO=1.4 DJANGOCMS=3
    - python: 3.4
      env: DJANGO=1.6 DJANGOCMS=3

install:
  - pip install -q -r "test_requirements/django-$DJANGO.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' || $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install https://github.com/pferate/google-api-python-client/archive/python3.zip; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install google-api-python-client==1.3.1; fi

script:
  - coverage run ./runtests.py
  - coverage report

after_success:
  - coveralls